config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :spendings
  resources :shares, only: [:index, :new, :create]

  root to: 'users#index'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :spendings
  has_many :users, through: :spendings

  validates :name, presence: true, format: { with: /\A[a-zA-Z ]+\z/ }
end

app/models/share.rb
class Share < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :recipient, class_name: 'User'

  validates :author_id, presence: true
  validates :recipient_id, presence: true
end

app/models/spending.rb
class Spending < ApplicationRecord
  belongs_to :user
  belongs_to :category

  validates :amount, presence: true, numericality: { only_integer: false }

  scope :for_user, ->(user) { where(user_id: user.id) } # use in to return current user spendings
  scope :by_category, ->(category) { where(category_id: category) if category.present? }
  scope :by_amount, -> (min, max) { where('CAST(amount AS DECIMAL) >= ? AND CAST(amount AS DECIMAL) <= ?', min.to_i, max.to_i) if min.present? && max.present? }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :spendings
  has_many :categories, through: :spendings

  has_many :authors, class_name: 'Share', foreign_key: :author_id
  has_many :recipients, class_name: 'Share', foreign_key: :recipient_id

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/shares_controller.rb
class SharesController < ApplicationController
  before_action :authenticate_user!

  def index
    @shared_lists = current_user.recipients
    @shared_spendings = Spending.includes(:category, :user).where(user_id: @shared_lists.pluck(:author_id))
  end

  def new
    @share = Share.new
  end

  def create
    @share = Share.new(share_params)

    recipient_id = find_user_by_email(share_params[:recipient_id])
    @share.recipient_id = recipient_id if recipient_id

    if @share.save
      redirect_to root_path, notice: I18n.t('shares.success')
    else
      redirect_to root_path, alert: I18n.t('shares.error')
    end
  end

  private

  def share_params
    params.require(:share).permit(:author_id, :recipient_id)
  end

  def find_user_by_email(email)
    recipient  = User.find_by(email: email)
    recipient&.id
  end
end

app/controllers/spendings_controller.rb
class SpendingsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_spending, only: [:show, :edit, :update, :destroy]

  has_scope :for_user
  has_scope :by_category
  has_scope :by_amount, using: %i[min max], type: :hash

  def index
    @user_spendings = apply_scopes(Spending.for_user(current_user)).includes(:category).all
  end

  def new
    @spending = Spending.new
    @categories = Category.all
  end

  def create
    @spending = Spending.new(spending_params)
    if @spending.save
      redirect_to root_path, notice: I18n.t('spendings.success')
    else
      redirect_to root_path, alert: I18n.t('spendings.error')
    end
  end

  def show
  end

  def edit
    @categories = Category.all
  end

  def update
    if current_user == @spending.user
      if @spending.update(spending_params)
        redirect_to :root
      else
        render :edit
      end
    else
      redirect_to :root, alert: I18n.t('spendings.edit')
    end
  end

  def destroy
    if current_user == @spending.user
      @spending.destroy
      redirect_to :root
    else
      redirect_to :root, alert: I18n.t('spendings.delete')
    end
  end

  private

  def find_spending
    @spending = Spending.find(params[:id])
  end

  def spending_params
    params.require(:spending).permit(:amount, :description, :user_id, :category_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  has_scope :for_user
  has_scope :by_category
  has_scope :by_amount, using: %i[min max], type: :hash


  def index
    @user = current_user
    @categories = Category.all
    @user_spendings = apply_scopes(Spending.for_user(current_user)).includes(:category).all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/shares_helper.rb
module SharesHelper
end

app/helpers/spendings_helper.rb
module SpendingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def total_spending_amount(user)
    # user&.spendings.sum(:amount)
    user&.spendings.sum { |spending| spending.amount.to_f }
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FTLTestTask</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if notice %>
      <p class="alert alert-success mt-5 w-25 mx-auto mt-3"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger w-25 mx-auto mt-3"><%= alert %></p>
    <% end %>

    <%= yield %>

  </body>
</html>

app/views/partials/_filters.html.erb
<%= form_tag path, method: :get do %>
    <div class="d-flex justify-content-between mb-3 p-3 form-group">
        <div class="d-flex flex-column form-group">
            <%= label_tag :by_category, "Category", class: "form-label" %>
            <%= select_tag :by_category, options_for_select(Category.all.map { |c| [c.name, c.id] }, params[:by_category]), include_blank: "Select", class: "form-select", id: "filter_category" %>
        </div>
        <div class="d-flex flex-column">
            <%= label_tag "by_amount[min]", "Min Amount", class: "form-label" %>
            <%= text_field_tag "by_amount[min]", params.dig(:by_amount, :min), class: "form-control", id: "min_amount" %>
        </div>
        <div class="d-flex flex-column">
            <%= label_tag "by_amount[max]", "Max Amount", class: "form-label" %>
            <%= text_field_tag "by_amount[max]", params.dig(:by_amount, :max), class: "form-control", id: "max_amount" %>
        </div>
        <%= submit_tag I18n.t("btns.filter"), class: "btn btn-primary w-25" %>
    </div>
<% end %>

app/views/partials/_form.html.erb
<%= form_with(model: spending, url: path, data: { turbo: false }, class: "d-flex flex-column") do |f| %>
    <div class="">
        <p><%= f.label :amount %>*</p>
        <%= f.text_field :amount, class: "form-control", id: "amount" %>
    </div>

    <div class="mt-4">
        <p><%= f.label :description %></p>
        <%= f.text_field :description, class: "form-control", id: "description" %>
    </div>

    <%= f.hidden_field :user_id, value: current_user.id, id: "user" %>

    <div class="mt-4">
        <p><%= f.label :category %></p>
        <%= f.collection_select :category_id, @categories, :id, :name, {prompt: I18n.t("forms.select")}, { class: "form-select", id: "category" } %>
    </div>

    <%= f.submit button_text, class: "mt-4 btn btn-primary w-100" %>
<% end %>

app/views/partials/_shares_form.html.erb
<%= form_with(model: Share.new, url: shares_path, data: { turbo: false }, class: "d-flex flex-column border border-black-subtle rounded mb-3") do |f| %>
    <div class="d-flex justify-content-between p-3 form-group gap-3">
        <div class="d-flex flex-column form-group">
            <%= f.hidden_field :author_id, value: current_user.id, id: 'author_id' %>
        </div>
        <div class="w-75">
            <p><%= f.label 'share with' %></p>
            <%= f.text_field :recipient_id, placeholder: "@example.com", id: 'recipient_id', class: "form-control" %>
        </div>
        <%= f.submit I18n.t("btns.share"), class: "btn btn-primary w-25 pt-3 pb-3" %>
    </div>
<% end %>

app/views/shares/index.html.erb
<h1 class="text-center mt-5 mb-3"><%= I18n.t("shares.title") %></h1>

 <div class="d-flex flex-column container">
    <% @shared_spendings.group_by(&:user).each do |user, spendings| %>
        <p class="fw-bolder"><%= I18n.t("shares.user") %> <%= user.email %></p>
        <% spendings.each do |spending| %>
        <div class="list-group-item mb-3 bg-body-tertiary p-3 rounded">
            <h3><%= spending&.amount %></h3>
            <p><%= spending&.description %></p>
            <p><%= spending&.category.name %></p>
        </div>
        <% end %>
    <% end %>
</div>

app/views/shares/new.html.erb
<%= form_with(model: Share.new, url: shares_path, data: { turbo: false }, class: "d-flex flex-column") do |f| %>
    <div class="d-flex justify-content-between mb-3 p-3 form-group">
        <div class="d-flex flex-column form-group">
            <%= f.hidden_field :author_id, value: current_user.id %>
        </div>
        <div class="mt-4">
            <p><%= f.label :recipient_id %></p>
            <%= f.text_field :recipient_id %>
        </div>
        <%= f.submit I18n.t("btns.share"), class: "btn btn-primary w-25" %>
    </div>
<% end %>

app/views/spendings/edit.html.erb
<h1 class="text-center mt-5 mb-5"><%= I18n.t("spendings.title_edit") %></h1>

<div class="w-50 mx-auto">
    <%= render 'partials/form', spending: @spending, button_text: "Edit Spending", path: spending_path(@spending) %>

    <div class="d-flex gap-3 mb-5 mt-4">
        <%= link_to I18n.t("btns.back_to_spendings"), root_path, class:"btn btn-outline-primary mx-auto" %>
    </div>
</div>

app/views/spendings/index.html.erb
<div class="container mt-5 mb-5">
    <div class="mb-5">
        <%= render 'partials/filters', path: spendings_path %>
    </div>

    <% @user_spendings.each do |spending| %>
        <div class="mt-1 mb-1 p-3 rounded bg-light d-flex justify-content-between">
            <div>
                <p class="fs-5"><%= I18n.t("spendings.amount") %> <%= spending&.amount %></p>
                <p><%= I18n.t("spendings.description") %> <%= spending&.description %></p>
                <p><%= I18n.t("spendings.category") %> <%= spending&.category.name %></p>
            </div>
            <div class="float-end">
                <%= link_to I18n.t("btns.edit"), edit_spending_path(spending), class:"btn mb-2 btn-secondary w-100" %>
                <%= button_to I18n.t("btns.delete"), spending, method: :delete, data: { turbo_confirm: 'Are you sure?' }, class:"btn btn-danger" %>
            </div>
        </div>
    <% end %>
</div>

app/views/spendings/new.html.erb
<h1 class="text-center mt-5 mb-5"><%= I18n.t("spendings.title_new") %></h1>
<div class="d-flex flex-column col-4 mx-auto">
    <%= render 'partials/form', categories: @categories, spending: Spending.new, path: spendings_path, button_text: t("spendings.add_spending") %>
</div>

app/views/spendings/show.html.erb
<div class="container">
    <h1 class="mt-5 mb-5"><%= I18n.t("spendings.title_show") %></h1>
    <div class="d-flex row">
        <div class="d-flex flex-column col-8">
            <div class="mt-1 mb-1 p-3 rounded bg-light d-flex justify-content-between">
                <div>
                    <p class="fs-5"><%= I18n.t("spendings.amount") %><%= @spending.amount %></p>
                    <p><%= I18n.t("spendings.description") %><%= @spending.description %></p>
                    <p><%= I18n.t("spendings.category") %><%= @spending.category.name %></p>
                </div>
                <div class="float-end">
                    <%= link_to I18n.t("btns.edit"), edit_spending_path(@spending), class:"btn mb-2 btn-secondary w-100" %>
                    <%= button_to I18n.t("btns.delete"), @spending, method: :delete, data: { turbo_confirm: 'Are you sure?' }, class:"btn btn-danger" %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/users/index.html.erb
<div class="container">
    <h1 class="mt-5 mb-5"><%= I18n.t("users.title") %></h1>
    <div class="d-flex row">
        <div class="d-flex flex-column col-8">
            <div>
                <%= render 'partials/filters', path: root_path %>
            </div>

            <h5 class="bg-secondary-subtle rounded p-2 mb-4"><%= I18n.t("users.total") %><%= total_spending_amount(current_user) %></h5>

            <div>
                <h4 class="mt-3 mb-3"><%= I18n.t("users.share_with") %></h4>
                <%= render 'partials/shares_form' %>
            </div>

            <% @user_spendings.each do |spending| %>
                <div class="mt-1 mb-1 p-3 rounded bg-light d-flex justify-content-between">
                    <div>
                        <p class="fs-5"><%= I18n.t("spendings.amount") %><%= spending&.amount %></p>
                        <p><%= I18n.t("spendings.description") %><%= spending&.description %></p>
                        <p><%= I18n.t("spendigns.category") %><%= spending&.category.name %></p>
                    </div>
                    <div class="float-end">
                        <%= link_to I18n.t("btns.edit"), edit_spending_path(spending), class:"btn mb-2 btn-secondary w-100" %>
                        <%= button_to I18n.t("btns.delete"), spending, method: :delete, data: { turbo_confirm: 'Are you sure?' }, class:"btn btn-danger" %>
                    </div>
                </div>
            <% end %>
        </div>

        <div class="d-flex flex-column col-4">
            <%= render 'partials/form', spending: Spending.new, button_text: t("spendings.add_spending"), path: spendings_path %>
            <%= button_to I18n.t("btns.sign_out"), destroy_user_session_path, method: :delete, class:"btn btn-danger mt-5 pt-3 pb-3 w-100" %>
        </div>
    </div>
</div>